### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by reyamir** [rust-nostr/nostr-sdk-swift#3]
I've tried to use Nostr SDK in my SwiftUI app, but when compile, I've got a lot of errors

<img width="289" alt="Screenshot 2024-11-15 at 10 16 37" src="https://github.com/user-attachments/assets/6c6eedd1-a8de-4b4f-9a9d-e89296ce4df1">

My simple code:

Init
```swift
import SwiftUI
import SwiftData
import NostrSDK

@Observable
class Nostr {
  var client: Client = ClientBuilder.init().database(database: try! NostrDatabase.lmdb(path: "nostr.db")).build();
}

@main
struct SampleApp: App {
  @State private var nostr = Nostr()
	
  var body: some Scene {
    WindowGroup {
      ContentView().environment(nostr)
    }
  }
}
```

Just get the nostr state
```swift
struct ContentView: View {
  @Environment(Nostr.self) private var nostr

  var body: some View {
    NavigationSplitView {
      List {
      }
      .navigationSplitViewColumnWidth(min: 180, ideal: 200)
      } detail: {
        Text("Select an item")
      }
  }
}
```

**Comment by reyamir** [comment]
Maybe related to this issue? https://github.com/mozilla/uniffi-rs/issues/2108

**Comment by yukibtc** [comment]
> Maybe related to this issue? [mozilla/uniffi-rs#2108](https://github.com/mozilla/uniffi-rs/issues/2108)

I don't think, because I'm not using nested errors in bindings.

I opened a PR with a possible fix here: https://github.com/rust-nostr/nostr/pull/633
I haven't a mac so I can't try it, are you able to test it? You can follow these steps for compilation: https://github.com/rust-nostr/nostr/tree/master/bindings/nostr-sdk-ffi#swift

Later, instead of use the package from the git repo, point it to `/path/to/nostr/bindings/nostr-sdk-ffi/swift` dir.

If it works, I'll publish the fix.

**Comment by reyamir** [comment]
I still got same error

**Comment by yukibtc** [comment]
I think the issue should be fixed. At least, the previous error is no longer returned in the CI, now it return linking errors when running `swift test`, but I'm not sure if this is related to the GitHub Actions or is effectively an issue in the Swift Package (I not found a way to make the `swift test` works).

Can you let me know if now works? The `fix-swift` branch in https://github.com/rust-nostr/nostr repo.

**Comment by reyamir** [comment]
Hi, this issue is fixed. I will add Example for Nostr Swift soon

**Comment by reyamir** [comment]
<img width="1191" alt="image" src="https://github.com/user-attachments/assets/e4cdf4a5-b080-4930-8298-869e17d31b97">
I've got a other error which say "UniFFI API checksum mismatch", but I not sure it related to your fixes or not. I've tried rebuild project but still not work.

**Comment by yukibtc** [comment]
Maybe I found the issue: the `uniffi_checksum_derive` crate was at another version (0.28.2 instead of 0.28.0, selected automatically). I'll publish a fix soon.

**Comment by yukibtc** [comment]
I pushed the fix. The CI still fail, but hope the "UniFFI API checksum mismatch" error is fixed.

**Comment by yukibtc** [comment]
I've finally fixed all the CI issues. I can now see the "Uniffi API checksum mismatch" error. It's weird that this happen only in Swift and not in Python or Kotlin. I opened an issue on the UniFFI repo: https://github.com/mozilla/uniffi-rs/issues/2321

**Comment by yukibtc** [comment]
@reyamir, finally I should have fixed the issue. I forked `uniffi` and removed the checksum validation for Swift. This is a temp solution until they'll fix the issue or allow to disable the checksum (https://github.com/mozilla/uniffi-rs/issues/2255). The CI is now passing. Before merge it, can you confirm it works on your side? Still in `fix-swift` branch.
